#!/bin/bash

check_dependencies() {
  local DEPENDENCIES=(curl feh)

  for dep in "${DEPENDENCIES[@]}"; do
    if [[ -z $(command -v ${dep}) ]]; then
      echo "Missing dependency: ${dep}"
      exit 1
    fi
  done
}

cleanup() {
  local TITLE="${1}"

  echo "Program interupted...cleaning up..."
  for dir in "${TITLE}" readmtmp; do
    rm -rf ${dir}
  done
  echo "Cleanup finished. Please try again."
}

tear_down() {
  echo "Cleaning up..."
  rm -rf readmtmp
}

num_to_title() {
  local URL="https://www.readm.org/manga/${1}"
  curl -s "${URL}" > title-temp
  local TITLE=$(grep '<title>' title-temp)
  rm title-temp
  TITLE="${TITLE##    <title>}" # trim leading whitespace and tag
  TITLE="${TITLE%%</title>}"    # trim trailing tag
  echo "${TITLE// /-}"
}

setup() {
  local TITLE="${1}"

  mkdir readmtmp
  mkdir "${TITLE}"
}


main() {
  local BASE_URL='https://www.readm.org/uploads/chapter_files'
  local BOOK_NUM="${1}"
  local CHAPTER_NUM="${2}"

  setup $(num_to_title ${BOOK_NUM})

  #curl -s "${BASE_URL}/${BOOK_NUM}/${CHAPTER_NUM}/1.jpg" > test.jpg
}

trap "cleanup ${3}" 1 2 3 6 15

check_dependencies
main $@
